### ISSUE TITLE
Error with /bin/s6-svscan

### ISSUE THREAD

**Issue by LM1LC3N7** [Wonderfall/docker-ghost#2]
Hello,

Something weird happened at launch, I can't figured why:

```bash
>>> wonderfall/ghost container <<<

> Initializing content folder...
> Applying preferences...
> Updating permissions... (SKIPPED)
> Executing process...
Error loading shared library libs6.so.2.7: Permission denied (needed by /bin/s6-svscan)
Error loading shared library libskarnet.so.2.6: Permission denied (needed by /bin/s6-svscan)
Error relocating /bin/s6-svscan: strerr_diesys: symbol not found
Error relocating /bin/s6-svscan: selfpipe_init: symbol not found
Error relocating /bin/s6-svscan: tain_add: symbol not found
Error relocating /bin/s6-svscan: tain_less: symbol not found
Error relocating /bin/s6-svscan: fd_read: symbol not found
Error relocating /bin/s6-svscan: strerr_warn: symbol not found
Error relocating /bin/s6-svscan: fd_close: symbol not found
Error relocating /bin/s6-svscan: iopause_stamp: symbol not found
Error relocating /bin/s6-svscan: tain_addsec: symbol not found
Error relocating /bin/s6-svscan: tain_now: symbol not found
Error relocating /bin/s6-svscan: child_spawn0: symbol not found
Error relocating /bin/s6-svscan: s6_supervise_lock: symbol not found
Error relocating /bin/s6-svscan: strerr_warnsys: symbol not found
Error relocating /bin/s6-svscan: pipe_internal: symbol not found
Error relocating /bin/s6-svscan: waitpid_nointr: symbol not found
Error relocating /bin/s6-svscan: selfpipe_read: symbol not found
Error relocating /bin/s6-svscan: sig_name: symbol not found
Error relocating /bin/s6-svscan: selfpipe_trapset: symbol not found
Error relocating /bin/s6-svscan: tain_from_millisecs: symbol not found
Error relocating /bin/s6-svscan: strerr_die: symbol not found
Error relocating /bin/s6-svscan: xpathexec_run: symbol not found
Error relocating /bin/s6-svscan: subgetopt_r: symbol not found
Error relocating /bin/s6-svscan: uint320_scan_base: symbol not found
Error relocating /bin/s6-svscan: skasigaction: symbol not found
Error relocating /bin/s6-svscan: fd_move: symbol not found
Error relocating /bin/s6-svscan: selfpipe_finish: symbol not found
Error relocating /bin/s6-svscan: sanitize_read: symbol not found
Error relocating /bin/s6-svscan: dir_close: symbol not found
Error relocating /bin/s6-svscan: STAMP: symbol not found
Error relocating /bin/s6-svscan: PROG: symbol not found
Error relocating /bin/s6-svscan: tain_infinite_relative: symbol not found
Error relocating /bin/s6-svscan: SKASIG_IGN: symbol not found
```

**Comment by LM1LC3N7** [comment]
It seems that libc (alpine version) is not compatible with s6? (Source: https://stackoverflow.com/a/53875399)

**Comment by LM1LC3N7** [comment]
I tried also this to install s6: https://github.com/just-containers/s6-overlay/issues/222#issue-275174741

```bash
	&& wget -O /tmp/s6-overlay.tar.gz https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz \
	&& tar xzf /tmp/s6-overlay.tar.gz -C / \
	&& rm -f /tmp/s6-overlay.tar.gz \
```

Now the error is:

```bash
>>> wonderfall/ghost container <<<

> Initializing content folder...
> Applying preferences...
> Updating permissions... (SKIPPED)
> Executing process...
s6-svscan: fatal: unable to chdir: Permission denied
```

**Comment by LM1LC3N7** [comment]
The problem is not because of `s6` incompatibility but is caused by  `su-exec ${UID} ${GID}`.

When I execute `S6` as `root` (only for testing!) there is no errors (in `/usr/local/bin/run.sh`):

```bash
# Run as root FOR TESTING ONLY
exec /bin/s6-svscan /etc/s6.d
```

I found that permissions on `/bin/s6-svscan` seems incorrect (`root:root`) and are not changed by the run script:

```bash
echo "> Updating permissions..."
chown -R ${UID}:${GID} /ghost /etc/s6.d
```

I don't think that `/bin/s6-svscan` can be started with `su-exec ${UID}:${GID}` if it belong to `root`.

So I tried to update the run script:

```bash
echo "> Updating permissions..."
chown -R ${UID}:${GID} /ghost /etc/s6.d /bin/s6*
```
Permissions are applied:
```bash
# ls -alh /bin/s6-*
-rwxr-xr-x    1 991      991        13.6K Dec 17 17:04 /bin/s6-tai64nlocal
```
But the error is the same:
```bash
/ghost # exec su-exec ${UID}:${GID} /bin/s6-svscan /etc/s6.d
Error loading shared library libs6.so.2.7: Permission denied (needed by /bin/s6-svscan)
Error loading shared library libskarnet.so.2.7: Permission denied (needed by /bin/s6-svscan)
Error relocating /bin/s6-svscan: strerr_diesys: symbol not found
Error relocating /bin/s6-svscan: selfpipe_init: symbol not found
Error relocating /bin/s6-svscan: tain_add: symbol not found
Error relocating /bin/s6-svscan: tain_less: symbol not found
Error relocating /bin/s6-svscan: fd_read: symbol not found
Error relocating /bin/s6-svscan: strerr_warn: symbol not found
Error relocating /bin/s6-svscan: fd_close: symbol not found
Error relocating /bin/s6-svscan: iopause_stamp: symbol not found
Error relocating /bin/s6-svscan: tain_addsec: symbol not found
Error relocating /bin/s6-svscan: tain_now: symbol not found
Error relocating /bin/s6-svscan: child_spawn0: symbol not found
Error relocating /bin/s6-svscan: s6_supervise_lock: symbol not found
Error relocating /bin/s6-svscan: strerr_warnsys: symbol not found
Error relocating /bin/s6-svscan: pipe_internal: symbol not found
Error relocating /bin/s6-svscan: waitpid_nointr: symbol not found
Error relocating /bin/s6-svscan: selfpipe_read: symbol not found
Error relocating /bin/s6-svscan: sig_name: symbol not found
Error relocating /bin/s6-svscan: selfpipe_trapset: symbol not found
Error relocating /bin/s6-svscan: tain_from_millisecs: symbol not found
Error relocating /bin/s6-svscan: strerr_die: symbol not found
Error relocating /bin/s6-svscan: xpathexec_run: symbol not found
Error relocating /bin/s6-svscan: subgetopt_r: symbol not found
Error relocating /bin/s6-svscan: fd_write: symbol not found
Error relocating /bin/s6-svscan: uint320_scan_base: symbol not found
Error relocating /bin/s6-svscan: skasigaction: symbol not found
Error relocating /bin/s6-svscan: fd_move: symbol not found
Error relocating /bin/s6-svscan: selfpipe_finish: symbol not found
Error relocating /bin/s6-svscan: sanitize_read: symbol not found
Error relocating /bin/s6-svscan: dir_close: symbol not found
Error relocating /bin/s6-svscan: STAMP: symbol not found
Error relocating /bin/s6-svscan: PROG: symbol not found
Error relocating /bin/s6-svscan: tain_infinite_relative: symbol not found
Error relocating /bin/s6-svscan: SKASIG_IGN: symbol not found
```
Starting as root is still working:
```bash
/ghost # exec /bin/s6-svscan /etc/s6.d
(node:35) Warning: a promise was created in a handler at /ghost/node_modules/tarn/lib/Pool.js:310:24 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/ghost/node_modules/bluebird/js/release/promise.js:79:10)
(node:35) Warning: a promise was created in a handler at /ghost/node_modules/tarn/lib/Pool.js:280:14 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/ghost/node_modules/bluebird/js/release/promise.js:79:10)
(node:35) Warning: a promise was created in a handler at /ghost/node_modules/tarn/lib/Pool.js:197:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.fromNode.Promise.fromCallback (/ghost/node_modules/bluebird/js/release/promise.js:177:9)
[2019-02-05 09:27:33] INFO Finished database init!
```

My last try was to only set the UID and not the GID:

```bash
echo "> Updating permissions..."
chown -R ${UID} /ghost /etc/s6.d
```
And this is working (as $UID user).

Any thoughts why setting the GID is not working?

**Comment by LM1LC3N7** [comment]
I have FINALY understand the problem: this is because of the UID and GID values (991, as suggested in the README).
I change 991 to 1337 (random number > 1000) and the problem is solved.

@Wonderfall can you explain how and why you suggest 991?

Also, I suggest adding this to help people understand why `Updating permissions` is so long:

```bash
NB_FILES=$(find /ghost -type f | wc -l)
echo "Updating permissions (will be long, as there is at least ${NB_FILES} files."
```

**Comment by LM1LC3N7** [comment]
I have FINALY understand the problem: this is because of the UID and GID values (991, as suggested in the README).

1. I have removed from the `Dockerfile`: `ARG UID=991` and `ARG GID=991`
2. I have changed the environment variable of the container from 991 to 1002 (random number > 1000) 

Problem solved!

@Wonderfall can you explain how and why you suggest 991? And maybe why setting the env in the dockerfile doesn't work for me?

Also, I suggest adding this to help people understand why `Updating permissions` is so long:

```bash
NB_FILES=$(find /ghost -type f | wc -l)
echo "Updating permissions (it will be long, as there is ${NB_FILES} files)."
```
Example:
```bash
>>> wonderfall/ghost container <<<

> Initializing content folder...
> Applying preferences...
> Updating permissions... (it will be long, as there is 17337 files).
```

**Comment by LM1LC3N7** [comment]
I tried to clone your project, create the docker image locally and start my container: same error.
The only solution is to download your image from hub.docker.com or change the startup command to remove `GID`:

```shell
echo "> Updating permissions..."
chown -R ${UID} /ghost /etc/s6.d
```


I really, really don't understand why I can't I have a valid image from your Dockerfile.
